spring.application.name=api-gateway
server.port=8090

jwt.secret=YOURSECRET

# CORE SERVICE (8081)
spring.cloud.gateway.routes[0].id=core-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**,/api/menus/**,/api/categories/**,/api/promos/**,/api/favorites/**,/api/reviews/**,/api/reports/**,/api/dashboard/**,/api/roles/**,/api/emails/**

# ORDER SERVICE (8082)
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**,/api/payments/**,/api/tables/**

# CONTENT SERVICE (8083)
spring.cloud.gateway.routes[2].id=content-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/careers/**,/api/locations/**,/api/banners/**,/api/applicants/**

# CORS CONFIGURATION
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true